services:
  - type: web
    name: psi-09-roastbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false

